import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Footer } from '@/components/layouts/footer'
import { Header } from '@/components/layouts/header'

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Marca | Início',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-sans text-gray-900 bg-gray-50 scroll-smooth scrollbar-thin scrollbar-track-gray-300 scrollbar-thumb-gray-100`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
